mock_variables = {
  "google_auth_type": "service_account",
  "google_auth_project_id": "",
  "google_auth_private_key_id": "",
  "google_auth_private_key": "",
  "google_auth_client_email": "",
  "google_auth_client_id": "",
  "google_auth_auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "google_auth_token_uri": "https://oauth2.googleapis.com/token",
  "google_auth_auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "google_auth_client_x509_cert_url": "",
  "spreadsheet_key_IntegrationTest": "1VWbIiRyZEIVUkoZAGCxX18MTq1eV1tic91V_focnCvw",
  "spreadsheet_key_FoodDaily": "1rpHCHOHrdWr7LzL4lbc7xxXzuQ_UAIMl26MU2fbzyvU",
  "spreadsheet_key_FoodCore": "1QDq6rDSosVcLE-TekFcxGDLqvbn_leVa5vUo8uJMTSI",
}